// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "base_block.proto" (package "chatbot", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { Timestamp } from "./google/protobuf/timestamp";
/**
 * @generated from protobuf message chatbot.Position
 */
export interface Position {
    /**
     * @generated from protobuf field: double x = 1
     */
    x: number;
    /**
     * @generated from protobuf field: double y = 2
     */
    y: number;
}
/**
 * @generated from protobuf message chatbot.Connections
 */
export interface Connections {
    /**
     * @generated from protobuf field: repeated string input = 1
     */
    input: string[];
    /**
     * @generated from protobuf field: repeated string output = 2
     */
    output: string[];
}
/**
 * @generated from protobuf message chatbot.BaseBlock
 */
export interface BaseBlock {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: string name = 2
     */
    name: string;
    /**
     * @generated from protobuf field: string icon = 3
     */
    icon: string;
    /**
     * @generated from protobuf field: chatbot.BlockType type = 4
     */
    type: BlockType;
    /**
     * @generated from protobuf field: chatbot.BlockStatus status = 5
     */
    status: BlockStatus;
    /**
     * @generated from protobuf field: double x = 6
     */
    x: number;
    /**
     * @generated from protobuf field: double y = 7
     */
    y: number;
    /**
     * @generated from protobuf field: double width = 8
     */
    width: number;
    /**
     * @generated from protobuf field: double height = 9
     */
    height: number;
    /**
     * @generated from protobuf field: string description = 10
     */
    description: string;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp createdAt = 11
     */
    createdAt?: Timestamp;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp updatedAt = 12
     */
    updatedAt?: Timestamp;
    /**
     * @generated from protobuf field: chatbot.Position position = 13
     */
    position?: Position;
    /**
     * @generated from protobuf field: chatbot.Connections connections = 14
     */
    connections?: Connections;
    /**
     * @generated from protobuf field: bool isInitializing = 15
     */
    isInitializing: boolean;
}
/**
 * @generated from protobuf enum chatbot.BlockStatus
 */
export enum BlockStatus {
    /**
     * @generated from protobuf enum value: ACTIVE = 0;
     */
    ACTIVE = 0,
    /**
     * @generated from protobuf enum value: ERROR = 1;
     */
    ERROR = 1,
    /**
     * @generated from protobuf enum value: NEW = 2;
     */
    NEW = 2,
    /**
     * @generated from protobuf enum value: DISABLED = 3;
     */
    DISABLED = 3,
    /**
     * @generated from protobuf enum value: NORMAL = 4;
     */
    NORMAL = 4
}
/**
 * @generated from protobuf enum chatbot.BlockType
 */
export enum BlockType {
    /**
     * @generated from protobuf enum value: TEXT_RESPONSE = 0;
     */
    TEXT_RESPONSE = 0,
    /**
     * @generated from protobuf enum value: USER_INPUT = 1;
     */
    USER_INPUT = 1,
    /**
     * @generated from protobuf enum value: TYPING_DELAY = 2;
     */
    TYPING_DELAY = 2,
    /**
     * @generated from protobuf enum value: CONVERSATIONAL_FORM = 3;
     */
    CONVERSATIONAL_FORM = 3,
    /**
     * @generated from protobuf enum value: MEDIA_BLOCK = 4;
     */
    MEDIA_BLOCK = 4,
    /**
     * @generated from protobuf enum value: LINK_STORY = 5;
     */
    LINK_STORY = 5,
    /**
     * @generated from protobuf enum value: JSON_API = 6;
     */
    JSON_API = 6
}
// @generated message type with reflection information, may provide speed optimized methods
class Position$Type extends MessageType<Position> {
    constructor() {
        super("chatbot.Position", [
            { no: 1, name: "x", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 2, name: "y", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ }
        ]);
    }
    create(value?: PartialMessage<Position>): Position {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.x = 0;
        message.y = 0;
        if (value !== undefined)
            reflectionMergePartial<Position>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Position): Position {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* double x */ 1:
                    message.x = reader.double();
                    break;
                case /* double y */ 2:
                    message.y = reader.double();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Position, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* double x = 1; */
        if (message.x !== 0)
            writer.tag(1, WireType.Bit64).double(message.x);
        /* double y = 2; */
        if (message.y !== 0)
            writer.tag(2, WireType.Bit64).double(message.y);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatbot.Position
 */
export const Position = new Position$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Connections$Type extends MessageType<Connections> {
    constructor() {
        super("chatbot.Connections", [
            { no: 1, name: "input", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "output", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<Connections>): Connections {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.input = [];
        message.output = [];
        if (value !== undefined)
            reflectionMergePartial<Connections>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Connections): Connections {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated string input */ 1:
                    message.input.push(reader.string());
                    break;
                case /* repeated string output */ 2:
                    message.output.push(reader.string());
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Connections, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated string input = 1; */
        for (let i = 0; i < message.input.length; i++)
            writer.tag(1, WireType.LengthDelimited).string(message.input[i]);
        /* repeated string output = 2; */
        for (let i = 0; i < message.output.length; i++)
            writer.tag(2, WireType.LengthDelimited).string(message.output[i]);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatbot.Connections
 */
export const Connections = new Connections$Type();
// @generated message type with reflection information, may provide speed optimized methods
class BaseBlock$Type extends MessageType<BaseBlock> {
    constructor() {
        super("chatbot.BaseBlock", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "icon", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "type", kind: "enum", T: () => ["chatbot.BlockType", BlockType] },
            { no: 5, name: "status", kind: "enum", T: () => ["chatbot.BlockStatus", BlockStatus] },
            { no: 6, name: "x", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 7, name: "y", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 8, name: "width", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 9, name: "height", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 10, name: "description", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 11, name: "createdAt", kind: "message", T: () => Timestamp },
            { no: 12, name: "updatedAt", kind: "message", T: () => Timestamp },
            { no: 13, name: "position", kind: "message", T: () => Position },
            { no: 14, name: "connections", kind: "message", T: () => Connections },
            { no: 15, name: "isInitializing", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<BaseBlock>): BaseBlock {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        message.name = "";
        message.icon = "";
        message.type = 0;
        message.status = 0;
        message.x = 0;
        message.y = 0;
        message.width = 0;
        message.height = 0;
        message.description = "";
        message.isInitializing = false;
        if (value !== undefined)
            reflectionMergePartial<BaseBlock>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: BaseBlock): BaseBlock {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* string name */ 2:
                    message.name = reader.string();
                    break;
                case /* string icon */ 3:
                    message.icon = reader.string();
                    break;
                case /* chatbot.BlockType type */ 4:
                    message.type = reader.int32();
                    break;
                case /* chatbot.BlockStatus status */ 5:
                    message.status = reader.int32();
                    break;
                case /* double x */ 6:
                    message.x = reader.double();
                    break;
                case /* double y */ 7:
                    message.y = reader.double();
                    break;
                case /* double width */ 8:
                    message.width = reader.double();
                    break;
                case /* double height */ 9:
                    message.height = reader.double();
                    break;
                case /* string description */ 10:
                    message.description = reader.string();
                    break;
                case /* google.protobuf.Timestamp createdAt */ 11:
                    message.createdAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.createdAt);
                    break;
                case /* google.protobuf.Timestamp updatedAt */ 12:
                    message.updatedAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.updatedAt);
                    break;
                case /* chatbot.Position position */ 13:
                    message.position = Position.internalBinaryRead(reader, reader.uint32(), options, message.position);
                    break;
                case /* chatbot.Connections connections */ 14:
                    message.connections = Connections.internalBinaryRead(reader, reader.uint32(), options, message.connections);
                    break;
                case /* bool isInitializing */ 15:
                    message.isInitializing = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: BaseBlock, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* string name = 2; */
        if (message.name !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.name);
        /* string icon = 3; */
        if (message.icon !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.icon);
        /* chatbot.BlockType type = 4; */
        if (message.type !== 0)
            writer.tag(4, WireType.Varint).int32(message.type);
        /* chatbot.BlockStatus status = 5; */
        if (message.status !== 0)
            writer.tag(5, WireType.Varint).int32(message.status);
        /* double x = 6; */
        if (message.x !== 0)
            writer.tag(6, WireType.Bit64).double(message.x);
        /* double y = 7; */
        if (message.y !== 0)
            writer.tag(7, WireType.Bit64).double(message.y);
        /* double width = 8; */
        if (message.width !== 0)
            writer.tag(8, WireType.Bit64).double(message.width);
        /* double height = 9; */
        if (message.height !== 0)
            writer.tag(9, WireType.Bit64).double(message.height);
        /* string description = 10; */
        if (message.description !== "")
            writer.tag(10, WireType.LengthDelimited).string(message.description);
        /* google.protobuf.Timestamp createdAt = 11; */
        if (message.createdAt)
            Timestamp.internalBinaryWrite(message.createdAt, writer.tag(11, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Timestamp updatedAt = 12; */
        if (message.updatedAt)
            Timestamp.internalBinaryWrite(message.updatedAt, writer.tag(12, WireType.LengthDelimited).fork(), options).join();
        /* chatbot.Position position = 13; */
        if (message.position)
            Position.internalBinaryWrite(message.position, writer.tag(13, WireType.LengthDelimited).fork(), options).join();
        /* chatbot.Connections connections = 14; */
        if (message.connections)
            Connections.internalBinaryWrite(message.connections, writer.tag(14, WireType.LengthDelimited).fork(), options).join();
        /* bool isInitializing = 15; */
        if (message.isInitializing !== false)
            writer.tag(15, WireType.Varint).bool(message.isInitializing);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatbot.BaseBlock
 */
export const BaseBlock = new BaseBlock$Type();
