// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "bot_block.proto" (package "chatbot", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message chatbot.BotBlock
 */
export interface BotBlock {
    /**
     * @generated from protobuf field: int32 botId = 1
     */
    botId: number;
    /**
     * @generated from protobuf field: string botName = 2
     */
    botName: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class BotBlock$Type extends MessageType<BotBlock> {
    constructor() {
        super("chatbot.BotBlock", [
            { no: 1, name: "botId", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "botName", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<BotBlock>): BotBlock {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.botId = 0;
        message.botName = "";
        if (value !== undefined)
            reflectionMergePartial<BotBlock>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: BotBlock): BotBlock {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 botId */ 1:
                    message.botId = reader.int32();
                    break;
                case /* string botName */ 2:
                    message.botName = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: BotBlock, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 botId = 1; */
        if (message.botId !== 0)
            writer.tag(1, WireType.Varint).int32(message.botId);
        /* string botName = 2; */
        if (message.botName !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.botName);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatbot.BotBlock
 */
export const BotBlock = new BotBlock$Type();
