// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "json_api_block.proto" (package "chatbot", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { ApiHeader } from "./button";
/**
 * @generated from protobuf message chatbot.JsonApiBlock
 */
export interface JsonApiBlock {
    /**
     * @generated from protobuf field: string type = 1
     */
    type: string; // "jsonApi"
    /**
     * @generated from protobuf field: string apiEndpoint = 2
     */
    apiEndpoint: string;
    /**
     * @generated from protobuf field: string requestType = 3
     */
    requestType: string; // "GET", "POST", etc.
    /**
     * @generated from protobuf field: repeated chatbot.ApiHeader apiHeaders = 4
     */
    apiHeaders: ApiHeader[];
}
// @generated message type with reflection information, may provide speed optimized methods
class JsonApiBlock$Type extends MessageType<JsonApiBlock> {
    constructor() {
        super("chatbot.JsonApiBlock", [
            { no: 1, name: "type", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "apiEndpoint", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "requestType", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "apiHeaders", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => ApiHeader }
        ]);
    }
    create(value?: PartialMessage<JsonApiBlock>): JsonApiBlock {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.type = "";
        message.apiEndpoint = "";
        message.requestType = "";
        message.apiHeaders = [];
        if (value !== undefined)
            reflectionMergePartial<JsonApiBlock>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: JsonApiBlock): JsonApiBlock {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string type */ 1:
                    message.type = reader.string();
                    break;
                case /* string apiEndpoint */ 2:
                    message.apiEndpoint = reader.string();
                    break;
                case /* string requestType */ 3:
                    message.requestType = reader.string();
                    break;
                case /* repeated chatbot.ApiHeader apiHeaders */ 4:
                    message.apiHeaders.push(ApiHeader.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: JsonApiBlock, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string type = 1; */
        if (message.type !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.type);
        /* string apiEndpoint = 2; */
        if (message.apiEndpoint !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.apiEndpoint);
        /* string requestType = 3; */
        if (message.requestType !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.requestType);
        /* repeated chatbot.ApiHeader apiHeaders = 4; */
        for (let i = 0; i < message.apiHeaders.length; i++)
            ApiHeader.internalBinaryWrite(message.apiHeaders[i], writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatbot.JsonApiBlock
 */
export const JsonApiBlock = new JsonApiBlock$Type();
