// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "text_response_block.proto" (package "chatbot", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { BaseBlock } from "./base_block";
/**
 * @generated from protobuf message chatbot.QuickReply
 */
export interface QuickReply {
    /**
     * @generated from protobuf field: string title = 1
     */
    title: string;
    /**
     * @generated from protobuf field: string value = 2
     */
    value: string;
}
/**
 * @generated from protobuf message chatbot.TextResponseBlock
 */
export interface TextResponseBlock {
    /**
     * @generated from protobuf field: chatbot.BaseBlock base = 1
     */
    base?: BaseBlock;
    /**
     * @generated from protobuf field: string content = 2
     */
    content: string;
    /**
     * @generated from protobuf field: repeated string alternateResponses = 3
     */
    alternateResponses: string[];
    /**
     * @generated from protobuf field: repeated chatbot.QuickReply quickReplies = 4
     */
    quickReplies: QuickReply[];
}
// @generated message type with reflection information, may provide speed optimized methods
class QuickReply$Type extends MessageType<QuickReply> {
    constructor() {
        super("chatbot.QuickReply", [
            { no: 1, name: "title", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "value", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<QuickReply>): QuickReply {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.title = "";
        message.value = "";
        if (value !== undefined)
            reflectionMergePartial<QuickReply>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: QuickReply): QuickReply {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string title */ 1:
                    message.title = reader.string();
                    break;
                case /* string value */ 2:
                    message.value = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: QuickReply, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string title = 1; */
        if (message.title !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.title);
        /* string value = 2; */
        if (message.value !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.value);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatbot.QuickReply
 */
export const QuickReply = new QuickReply$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TextResponseBlock$Type extends MessageType<TextResponseBlock> {
    constructor() {
        super("chatbot.TextResponseBlock", [
            { no: 1, name: "base", kind: "message", T: () => BaseBlock },
            { no: 2, name: "content", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "alternateResponses", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "quickReplies", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => QuickReply }
        ]);
    }
    create(value?: PartialMessage<TextResponseBlock>): TextResponseBlock {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.content = "";
        message.alternateResponses = [];
        message.quickReplies = [];
        if (value !== undefined)
            reflectionMergePartial<TextResponseBlock>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: TextResponseBlock): TextResponseBlock {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* chatbot.BaseBlock base */ 1:
                    message.base = BaseBlock.internalBinaryRead(reader, reader.uint32(), options, message.base);
                    break;
                case /* string content */ 2:
                    message.content = reader.string();
                    break;
                case /* repeated string alternateResponses */ 3:
                    message.alternateResponses.push(reader.string());
                    break;
                case /* repeated chatbot.QuickReply quickReplies */ 4:
                    message.quickReplies.push(QuickReply.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: TextResponseBlock, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* chatbot.BaseBlock base = 1; */
        if (message.base)
            BaseBlock.internalBinaryWrite(message.base, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* string content = 2; */
        if (message.content !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.content);
        /* repeated string alternateResponses = 3; */
        for (let i = 0; i < message.alternateResponses.length; i++)
            writer.tag(3, WireType.LengthDelimited).string(message.alternateResponses[i]);
        /* repeated chatbot.QuickReply quickReplies = 4; */
        for (let i = 0; i < message.quickReplies.length; i++)
            QuickReply.internalBinaryWrite(message.quickReplies[i], writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chatbot.TextResponseBlock
 */
export const TextResponseBlock = new TextResponseBlock$Type();
