/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 6.32.0
 * source: typing_delay_block.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
export namespace chatbot {
    export class TypingDelayBlock extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            type?: string;
            delaySeconds?: number;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("type" in data && data.type != undefined) {
                    this.type = data.type;
                }
                if ("delaySeconds" in data && data.delaySeconds != undefined) {
                    this.delaySeconds = data.delaySeconds;
                }
            }
        }
        get type() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set type(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get delaySeconds() {
            return pb_1.Message.getFieldWithDefault(this, 2, 0) as number;
        }
        set delaySeconds(value: number) {
            pb_1.Message.setField(this, 2, value);
        }
        static fromObject(data: {
            type?: string;
            delaySeconds?: number;
        }): TypingDelayBlock {
            const message = new TypingDelayBlock({});
            if (data.type != null) {
                message.type = data.type;
            }
            if (data.delaySeconds != null) {
                message.delaySeconds = data.delaySeconds;
            }
            return message;
        }
        toObject() {
            const data: {
                type?: string;
                delaySeconds?: number;
            } = {};
            if (this.type != null) {
                data.type = this.type;
            }
            if (this.delaySeconds != null) {
                data.delaySeconds = this.delaySeconds;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.type.length)
                writer.writeString(1, this.type);
            if (this.delaySeconds != 0)
                writer.writeDouble(2, this.delaySeconds);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): TypingDelayBlock {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new TypingDelayBlock();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.type = reader.readString();
                        break;
                    case 2:
                        message.delaySeconds = reader.readDouble();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): TypingDelayBlock {
            return TypingDelayBlock.deserialize(bytes);
        }
    }
}
