// ---------------------------------------------------------------------
// <copyright file="PageMessage.cs" company="Netlarx">
// Copyright (c) Netlarx softwares pvt ltd. All rights reserved.
// </copyright>
// ---------------------------------------------------------------------

namespace Netlarx.Products.Gobot.Models
{
    using System.Collections.Generic;

    public class StoryReference
    {
        public string Id { get; set; }
        public string Name { get; set; }
    }

    public class PageMessage
    {
        public string BotId { get; set; }
        public string Id { get; set; }   // Generated by backend
        public List<string> Urls { get; set; }
        public bool ShowAfterDelay { get; set; }
        public int Delay { get; set; }
        public string MessageType { get; set; }
        public string TextMessage { get; set; }
        // Story message type
        public StoryReference SelectedStory { get; set; }
    }
}
